runtime: python39
service: default

env_variables:
  GROQ_API_KEY: "your-groq-api-key-here"

automatic_scaling:
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto