name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # أو master حسب اسم الفرع

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_SA_KEY }}
          install_components: 'beta'


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
            --source . \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}
